-- Seed modules, lessons, and questions for SmartDrive Naija
-- Only inserts if modules table is empty

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM modules) = 0 THEN

    -- ============================================================
    -- MODULE 1: Road Signs & Signals (Free)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('road-signs', 'Road Signs & Signals', 'Learn all Nigerian road signs, traffic signals, and their meanings. Essential for safe driving and passing your theory test.', 'SignpostBig', 1, true, false, 45, 500);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (1, 'regulatory-signs', 'Regulatory Signs', '# Regulatory Signs\n\nRegulatory signs are traffic signs that instruct road users on what they must or must not do. They are typically circular with a red border.\n\n## Types of Regulatory Signs\n\n### Prohibitory Signs\nThese signs prohibit certain actions:\n- **No Entry** — Red circle with white horizontal bar\n- **No Parking** — Red circle with diagonal line through "P"\n- **No U-Turn** — Red circle with U-turn crossed out\n- **Speed Limit** — Red circle with number indicating max speed in km/h\n\n### Mandatory Signs\nThese signs indicate actions that must be taken:\n- **Keep Left/Right** — Blue circle with arrow\n- **Roundabout Ahead** — Blue circle with rotating arrows\n- **Minimum Speed** — Blue circle with number\n\n### Priority Signs\n- **Give Way** — Inverted triangle\n- **Stop** — Red octagon\n\n> **Important**: Disobeying regulatory signs is a traffic offence under the FRSC Act and can result in fines or license points.\n\n## Key Takeaways\n1. Circular signs with red borders are regulatory\n2. They are enforceable by law\n3. Always reduce speed when you see regulatory signs\n4. Ignorance of signs is not a valid excuse', 1, 15, 50, false, 15, NULL),

    (1, 'warning-signs', 'Warning Signs', '# Warning Signs\n\nWarning signs alert drivers to potential hazards or changes in road conditions ahead. They are typically triangular with a red border.\n\n## Common Warning Signs in Nigeria\n\n### Road Condition Warnings\n- **Bend Ahead** — Triangle with curved arrow\n- **Uneven Surface** — Triangle with bumpy road\n- **Slippery Road** — Triangle with car skidding\n- **Narrow Bridge** — Triangle showing bridge narrowing\n\n### Hazard Warnings\n- **Pedestrian Crossing** — Triangle with walking person\n- **School Zone** — Triangle with children\n- **Cattle Crossing** — Triangle with cow\n- **Falling Rocks** — Triangle with rocks\n\n### Junction Warnings\n- **Crossroads Ahead** — Triangle with cross\n- **T-Junction** — Triangle with T shape\n- **Y-Junction** — Triangle with Y shape\n- **Roundabout Ahead** — Triangle with circular arrows\n\n> **Tip**: When you see a warning sign, reduce your speed and be prepared to stop. Warning signs give you time to react safely.\n\n## Key Takeaways\n1. Triangular signs are warning signs\n2. They alert you to hazards ahead\n3. Always slow down when you see them\n4. They are not regulatory but ignoring them can be dangerous', 2, 15, 50, false, 15, NULL),

    (1, 'informational-signs', 'Informational Signs', '# Informational Signs\n\nInformational signs provide useful information to drivers about directions, distances, and services. They are typically rectangular.\n\n## Types of Informational Signs\n\n### Direction Signs\n- Show the direction to nearby towns and cities\n- Usually green or blue rectangles\n- Include distance information\n\n### Service Signs\n- **Hospital** — Sign with "H" or cross\n- **Fuel Station** — Sign with fuel pump\n- **Rest Area** — Sign with tree or bench\n- **Police Station** — Sign with police badge\n\n### Tourist Information\n- Brown signs indicating tourist attractions\n- Historical sites\n- National parks\n\n## Key Takeaways\n1. Rectangular signs are informational\n2. They help with navigation\n3. Green signs are for directions\n4. Blue signs indicate services', 3, 10, 50, false, 10, NULL);

    -- Questions for Module 1
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (1, 1, 'road-signs', 'multiple_choice', 'What shape are regulatory signs in Nigeria?', '["Circular","Triangular","Rectangular","Diamond"]', 0, 'Regulatory signs are typically circular with a red border. They instruct road users on what they must or must not do.', 1, true),
    (1, 1, 'road-signs', 'multiple_choice', 'What does a red octagon sign mean?', '["Give Way","Stop","No Entry","Speed Limit"]', 1, 'A red octagon means STOP. You must come to a complete stop and only proceed when it is safe to do so.', 1, true),
    (1, 1, 'road-signs', 'multiple_choice', 'Which sign prohibits parking?', '["Blue circle with P","Red circle with diagonal line through P","Yellow triangle with P","Green rectangle with P"]', 1, 'A red circle with a diagonal line through "P" is the No Parking sign. Parking in such areas can result in a fine.', 1, true),
    (1, 2, 'road-signs', 'multiple_choice', 'What shape are warning signs?', '["Circular","Triangular","Rectangular","Octagonal"]', 1, 'Warning signs are typically triangular with a red border. They alert drivers to potential hazards ahead.', 1, true),
    (1, 2, 'road-signs', 'multiple_choice', 'What does a triangle with children indicate?', '["Playground ahead","School zone","Children crossing","No children allowed"]', 2, 'A triangle with children indicates a school zone. Drivers should slow down and watch for children crossing the road.', 1, true),
    (1, 2, 'road-signs', 'multiple_choice', 'When you see a warning sign, you should:', '["Speed up","Maintain speed","Reduce speed and be prepared","Stop immediately"]', 2, 'Warning signs alert you to hazards ahead. You should reduce speed and be prepared to react safely.', 1, true),
    (1, 3, 'road-signs', 'multiple_choice', 'What color are directional information signs?', '["Red","Green","Yellow","Brown"]', 1, 'Directional information signs are typically green. They show directions to nearby towns and cities.', 1, true),
    (1, 3, 'road-signs', 'multiple_choice', 'What does a brown information sign indicate?', '["Hospital","Tourist attraction","Fuel station","Police station"]', 1, 'Brown signs indicate tourist attractions, historical sites, and national parks.', 1, true),
    (1, NULL, 'road-signs', 'multiple_choice', 'A blue circle with a rotating arrow means:', '["No entry","Roundabout ahead","Turn left","U-turn allowed"]', 1, 'A blue circle with rotating arrows indicates a roundabout ahead. Drivers should prepare to give way to traffic already in the roundabout.', 2, true),
    (1, NULL, 'road-signs', 'multiple_choice', 'Ignorance of road signs is:', '["A valid excuse","Not a valid excuse","Only valid for new drivers","Valid in rural areas"]', 1, 'Ignorance of road signs is not a valid excuse under the FRSC Act. All drivers are expected to know and understand road signs.', 2, true);

    -- ============================================================
    -- MODULE 2: Traffic Rules & Regulations (Free)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('traffic-rules', 'Traffic Rules & Regulations', 'Master Nigerian traffic laws, right-of-way rules, speed limits, and FRSC regulations. Critical for safe and legal driving.', 'ShieldCheck', 2, true, false, 60, 600);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (2, 'speed-limits', 'Speed Limits in Nigeria', '# Speed Limits in Nigeria\n\nSpeed limits are set to ensure road safety for all users. In Nigeria, different road types have different speed limits.\n\n## Standard Speed Limits\n\n| Road Type | Speed Limit |\n|-----------|------------|\n| Urban areas | 50 km/h |\n| Highways | 100 km/h |\n| Expressways | 120 km/h |\n| School zones | 30 km/h |\n| Residential areas | 30 km/h |\n\n## Factors Affecting Safe Speed\n\n1. **Weather conditions** — Reduce speed in rain or fog\n2. **Traffic density** — Slow down in heavy traffic\n3. **Road conditions** — Potholes and uneven surfaces\n4. **Time of day** — Be extra cautious at night\n5. **Pedestrian activity** — Watch for people crossing\n\n> **FRSC Rule**: Exceeding the speed limit by more than 20 km/h can result in a fine of ₦3,000 and 3 penalty points on your license.\n\n## Key Takeaways\n1. Always observe posted speed limits\n2. Reduce speed in adverse conditions\n3. School zones require extra caution (30 km/h)\n4. Speeding is one of the leading causes of accidents in Nigeria', 1, 20, 60, false, 20, NULL),

    (2, 'right-of-way', 'Right of Way Rules', '# Right of Way Rules\n\nUnderstanding right of way is essential for safe driving. It determines who proceeds first in different traffic situations.\n\n## Basic Right of Way Rules\n\n### At Intersections\n1. **At a T-junction**: Traffic on the major road has right of way\n2. **At a crossroads without signs**: Give way to traffic from the right\n3. **At a roundabout**: Give way to traffic already in the roundabout\n4. **At a controlled intersection**: Follow traffic lights or police signals\n\n### Emergency Vehicles\n- Always give way to emergency vehicles (ambulances, fire trucks, police)\n- Pull over to the left when you hear sirens\n- Do not block intersections for emergency vehicles\n\n### Pedestrians\n- Pedestrians at zebra crossings always have right of way\n- Slow down near school zones\n- Be prepared to stop for pedestrians at intersections\n\n> **Important**: Right of way is not a privilege — it is a responsibility. Even when you have right of way, you should exercise caution and be prepared to yield if necessary to avoid an accident.\n\n## Key Takeaways\n1. At roundabouts, give way to traffic already inside\n2. Emergency vehicles always have priority\n3. Pedestrians at zebra crossings have right of way\n4. At T-junctions, major road traffic has priority', 2, 20, 60, false, 20, NULL),

    (2, 'lane-discipline', 'Lane Discipline & Overtaking', '# Lane Discipline & Overtaking\n\nProper lane discipline and safe overtaking are crucial for road safety.\n\n## Lane Discipline\n\n### On Multi-Lane Roads\n- **Right lane**: For overtaking and faster traffic\n- **Left lane**: For normal driving\n- **Center lane**: For intermediate speeds\n- Always use your indicators when changing lanes\n\n### On Single-Lane Roads\n- Keep to the left side of the road\n- Do not straddle lane markings\n- Be aware of oncoming traffic\n\n## Safe Overtaking\n\n### Before Overtaking\n1. Check your mirrors and blind spots\n2. Ensure you have a clear view of the road ahead\n3. Make sure there is enough space to complete the maneuver\n4. Signal your intention\n\n### During Overtaking\n1. Accelerate briskly to pass quickly\n2. Keep a safe distance from the vehicle being overtaken\n3. Do not exceed the speed limit\n\n### After Overtaking\n1. Signal before moving back to the left\n2. Ensure you can see the overtaken vehicle in your mirror\n3. Move back to the left lane smoothly\n\n> **Dangerous**: Never overtake on a bend, at a junction, near a pedestrian crossing, or when visibility is poor. These are leading causes of head-on collisions in Nigeria.\n\n## Key Takeaways\n1. Keep left unless overtaking\n2. Always check blind spots before changing lanes\n3. Never overtake on bends or at junctions\n4. Signal before and after overtaking', 3, 20, 60, false, 20, NULL);

    -- Questions for Module 2
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (2, 1, 'traffic-rules', 'multiple_choice', 'What is the speed limit in urban areas in Nigeria?', '["40 km/h","50 km/h","60 km/h","80 km/h"]', 1, 'The speed limit in urban areas in Nigeria is 50 km/h. This helps ensure safety for pedestrians and other road users in built-up areas.', 1, true),
    (2, 1, 'traffic-rules', 'multiple_choice', 'What is the speed limit on Nigerian expressways?', '["80 km/h","100 km/h","120 km/h","140 km/h"]', 2, 'The speed limit on Nigerian expressways is 120 km/h. Always check for posted speed limits as they may vary.', 1, true),
    (2, 1, 'traffic-rules', 'multiple_choice', 'What is the speed limit in school zones?', '["20 km/h","30 km/h","40 km/h","50 km/h"]', 1, 'The speed limit in school zones is 30 km/h. Children may cross unexpectedly, so extra caution is needed.', 1, true),
    (2, 2, 'traffic-rules', 'multiple_choice', 'At a roundabout, who has right of way?', '["The vehicle entering","Traffic already in the roundabout","The larger vehicle","The faster vehicle"]', 1, 'Traffic already in the roundabout has right of way. Vehicles entering must give way to traffic already circulating.', 1, true),
    (2, 2, 'traffic-rules', 'multiple_choice', 'When an emergency vehicle approaches with sirens, you should:', '["Speed up to get out of the way","Pull over to the left and stop","Continue at the same speed","Stop immediately in your lane"]', 1, 'When an emergency vehicle approaches, pull over to the left and stop if safe. This allows the emergency vehicle to pass quickly and safely.', 1, true),
    (2, 2, 'traffic-rules', 'multiple_choice', 'At a zebra crossing, who has right of way?', '["The driver","The pedestrian","The larger vehicle","Whoever arrived first"]', 1, 'Pedestrians always have right of way at zebra crossings. Drivers must slow down and stop to let pedestrians cross safely.', 1, true),
    (2, 3, 'traffic-rules', 'multiple_choice', 'On a multi-lane road, which lane should you use for normal driving?', '["Right lane","Center lane","Left lane","Any lane"]', 2, 'The left lane is for normal driving. The right lane is for overtaking and faster traffic. Always keep left unless overtaking.', 1, true),
    (2, 3, 'traffic-rules', 'multiple_choice', 'When is it dangerous to overtake?', '["On a straight road","On a bend","In good weather","On a wide road"]', 1, 'Overtaking on a bend is extremely dangerous because you cannot see oncoming traffic. Never overtake on bends, at junctions, or near pedestrian crossings.', 1, true),
    (2, NULL, 'traffic-rules', 'multiple_choice', 'Exceeding the speed limit by more than 20 km/h in Nigeria can result in:', '["A warning only","A fine and penalty points","License suspension","No penalty"]', 1, 'Exceeding the speed limit by more than 20 km/h can result in a fine of ₦3,000 and 3 penalty points on your license under FRSC regulations.', 2, true),
    (2, NULL, 'traffic-rules', 'multiple_choice', 'Before changing lanes, you should:', '["Just signal and move","Check mirrors and blind spots, then signal","Honk and move","Speed up and cut in"]', 1, 'Always check your mirrors and blind spots, then signal before changing lanes. This ensures you are aware of other vehicles and communicate your intention.', 1, true);

    -- ============================================================
    -- MODULE 3: Vehicle Maintenance (Free)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('vehicle-maintenance', 'Vehicle Maintenance', 'Learn essential vehicle maintenance checks, routine servicing, and how to keep your vehicle roadworthy and safe.', 'Wrench', 3, true, false, 40, 400);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (3, 'daily-checks', 'Daily Vehicle Checks', '# Daily Vehicle Checks\n\nBefore driving, you should perform basic checks to ensure your vehicle is safe.\n\n## The POWDERY Checklist\n\n**P** — **Petrol/Fuel**: Check fuel level\n**O** — **Oil**: Check engine oil level\n**W** — **Water**: Check coolant and windshield washer\n**D** — **Damage**: Check for visible damage\n**E** — **Electrics**: Check lights, indicators, horn\n**R** — **Rubber**: Check tire condition and pressure\n**Y** — **Yourself**: Ensure you are fit to drive\n\n## Tire Safety\n\n### Tire Pressure\n- Check pressure when tires are cold\n- Recommended pressure is usually 30-35 PSI\n- Under-inflated tires reduce fuel efficiency and can burst\n- Over-inflated tires reduce grip\n\n### Tire Tread\n- Minimum legal tread depth is 1.6mm\n- Worn tires are dangerous, especially on wet roads\n- Check for cuts, bulges, or embedded objects\n\n> **Safety Tip**: A tire blowout at high speed can cause loss of control. Check your tires regularly — it could save your life.\n\n## Key Takeaways\n1. Use the POWDERY checklist daily\n2. Check tire pressure and tread regularly\n3. Ensure all lights are working\n4. Never drive with damaged or worn tires', 1, 15, 50, false, 15, NULL),

    (3, 'engine-care', 'Engine Care & Servicing', '# Engine Care & Servicing\n\nRegular engine maintenance extends the life of your vehicle and prevents breakdowns.\n\n## Oil Changes\n\n### When to Change Oil\n- Every 5,000 km or 3 months (whichever comes first)\n- Check oil level monthly using the dipstick\n- Use the recommended oil grade for your vehicle\n\n### Signs of Oil Problems\n- Oil warning light on dashboard\n- Dark, dirty oil on dipstick\n- Engine running louder than normal\n- Burning smell from engine\n\n## Coolant System\n\n- Check coolant level monthly\n- Top up with correct coolant mixture\n- Never open radiator cap when engine is hot\n- Watch for temperature gauge rising above normal\n\n## Air Filter\n\n- Replace every 20,000 km or annually\n- A clogged air filter reduces fuel efficiency\n- Check during every service\n\n> **Important**: Regular servicing by a qualified mechanic is essential. Delaying servicing can lead to costly repairs and dangerous failures.\n\n## Key Takeaways\n1. Change oil every 5,000 km or 3 months\n2. Check coolant monthly\n3. Replace air filter annually\n4. Never ignore warning lights on the dashboard', 2, 15, 50, false, 15, NULL),

    (3, 'brake-safety', 'Brake Safety', '# Brake Safety\n\nYour vehicle''s braking system is its most important safety feature.\n\n## Brake System Components\n\n1. **Brake pads** — Create friction to slow the vehicle\n2. **Brake discs/rotors** — Surface that pads press against\n3. **Brake fluid** — Transmits force from pedal to brakes\n4. **Brake lines** — Carry fluid to each wheel\n\n## Signs of Brake Problems\n\n- **Squeaking or grinding noise** — Worn brake pads\n- **Soft or spongy pedal** — Air in brake lines or low fluid\n- **Vehicle pulls to one side** — Uneven brake wear\n- **Longer stopping distance** — Worn pads or contaminated fluid\n- **Brake warning light** — System problem detected\n\n## Brake Maintenance\n\n- Check brake fluid level monthly\n- Replace brake pads every 40,000-50,000 km\n- Have brakes inspected at every service\n- Replace brake fluid every 2 years\n\n> **Critical**: Never drive with faulty brakes. If you notice any brake problems, stop driving immediately and have your vehicle towed to a mechanic.\n\n## Key Takeaways\n1. Brakes are your most important safety system\n2. Check brake fluid monthly\n3. Replace pads every 40,000-50,000 km\n4. Never ignore grinding noises or soft pedals', 3, 10, 50, false, 10, NULL);

    -- Questions for Module 3
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (3, 1, 'vehicle-maintenance', 'multiple_choice', 'What does the "P" in POWDERY checklist stand for?', '["Pressure","Petrol/Fuel","Parts","Park"]', 1, 'In the POWDERY checklist, "P" stands for Petrol/Fuel. Always check your fuel level before starting a journey.', 1, true),
    (3, 1, 'vehicle-maintenance', 'multiple_choice', 'What is the minimum legal tire tread depth?', '["1.0mm","1.6mm","2.0mm","3.0mm"]', 1, 'The minimum legal tire tread depth is 1.6mm. Worn tires with less tread are dangerous, especially on wet roads.', 1, true),
    (3, 1, 'vehicle-maintenance', 'multiple_choice', 'When should you check tire pressure?', '["When tires are hot","When tires are cold","After driving 10km","Anytime"]', 1, 'Tire pressure should be checked when tires are cold. Heat from driving increases pressure and gives inaccurate readings.', 1, true),
    (3, 2, 'vehicle-maintenance', 'multiple_choice', 'How often should you change engine oil?', '["Every 1,000 km","Every 5,000 km or 3 months","Every 10,000 km","Once a year"]', 1, 'Engine oil should be changed every 5,000 km or 3 months, whichever comes first. This keeps the engine lubricated and prevents wear.', 1, true),
    (3, 2, 'vehicle-maintenance', 'multiple_choice', 'When should you replace the air filter?', '["Every 5,000 km","Every 20,000 km or annually","Every 50,000 km","Never"]', 1, 'The air filter should be replaced every 20,000 km or annually. A clogged air filter reduces fuel efficiency and engine performance.', 1, true),
    (3, 3, 'vehicle-maintenance', 'multiple_choice', 'A squeaking noise when braking usually means:', '["Brakes are working well","Brake pads are worn","Brake fluid is low","Nothing serious"]', 1, 'A squeaking or grinding noise when braking usually means the brake pads are worn and need replacement. Have them checked immediately.', 1, true),
    (3, 3, 'vehicle-maintenance', 'multiple_choice', 'How often should brake fluid be replaced?', '["Every 6 months","Every 2 years","Every 5 years","Never"]', 1, 'Brake fluid should be replaced every 2 years. Old brake fluid can absorb moisture, reducing braking effectiveness.', 1, true),
    (3, NULL, 'vehicle-maintenance', 'multiple_choice', 'If the brake warning light comes on, you should:', '["Continue driving","Stop and have the vehicle checked","Ignore it if brakes feel normal","Drive slowly to your destination"]', 1, 'If the brake warning light comes on, stop driving immediately and have the vehicle checked. Driving with faulty brakes is extremely dangerous.', 1, true),
    (3, NULL, 'vehicle-maintenance', 'multiple_choice', 'Under-inflated tires can cause:', '["Better fuel efficiency","Reduced fuel efficiency and potential blowout","Better grip","No issues"]', 1, 'Under-inflated tires reduce fuel efficiency and can overheat, leading to a blowout. Always maintain correct tire pressure.', 2, true),
    (3, NULL, 'vehicle-maintenance', 'multiple_choice', 'Never open the radiator cap when:', '["The engine is cold","The engine is hot","The vehicle is parked","In the morning"]', 1, 'Never open the radiator cap when the engine is hot. The cooling system is under pressure and can spray boiling coolant, causing severe burns.', 2, true);

    -- ============================================================
    -- MODULE 4: Defensive Driving (Premium)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('defensive-driving', 'Defensive Driving', 'Advanced techniques for anticipating hazards, maintaining safe following distances, and driving defensively in all conditions.', 'Car', 4, false, true, 50, 700);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (4, 'following-distance', 'Safe Following Distance', '# Safe Following Distance\n\nMaintaining a safe following distance is one of the most important defensive driving skills.\n\n## The 3-Second Rule\n\n1. Watch the vehicle ahead pass a fixed point (e.g., a sign or pole)\n2. Count "one thousand one, one thousand two, one thousand three"\n3. If you reach the point before finishing counting, you are too close\n\n## Adjusting Following Distance\n\n| Condition | Following Distance |\n|-----------|-------------------|\n| Normal conditions | 3 seconds |\n| Wet roads | 4-5 seconds |\n| Fog or heavy rain | 5-6 seconds |\n| Behind large vehicles | 4-5 seconds |\n| At high speeds | 4+ seconds |\n\n## Why Following Distance Matters\n\n- Gives you time to react to sudden stops\n- Provides space for emergency maneuvers\n- Reduces the risk of rear-end collisions\n- Allows for brake failure margin\n\n> **Fact**: Rear-end collisions are among the most common accidents in Nigeria, often caused by following too closely.\n\n## Key Takeaways\n1. Use the 3-second rule in normal conditions\n2. Increase distance in bad weather\n3. Keep extra distance behind large vehicles\n4. Never tailgate — it is dangerous and illegal', 1, 15, 60, false, 15, NULL),

    (4, 'hazard-perception', 'Hazard Perception', '# Hazard Perception\n\nHazard perception is the ability to identify potential dangers on the road before they become emergencies.\n\n## Types of Hazards\n\n### Static Hazards\n- Road junctions\n- Pedestrian crossings\n- School zones\n- Narrow bridges\n- Road construction\n\n### Dynamic Hazards\n- Other vehicles changing lanes\n- Pedestrians stepping onto the road\n- Animals crossing\n- Cyclists\n- Parked cars with doors opening\n\n### Environmental Hazards\n- Wet or slippery roads\n- Fog reducing visibility\n- Sun glare\n- Potholes\n- Flooding\n\n## Scanning Technique\n\n1. **Look ahead** — Scan 12-15 seconds ahead\n2. **Check mirrors** — Every 5-8 seconds\n3. **Check blind spots** — Before changing direction\n4. **Watch for clues** — Ball rolling into road (child may follow), exhaust from parked car (door may open)\n\n> **Pro Tip**: Experienced drivers don''t just watch the car in front — they watch 2-3 cars ahead to anticipate what the car in front will do.\n\n## Key Takeaways\n1. Scan 12-15 seconds ahead\n2. Check mirrors every 5-8 seconds\n3. Watch for both static and dynamic hazards\n4. Anticipate what other road users might do', 2, 20, 60, false, 20, NULL),

    (4, 'night-driving', 'Night Driving Safety', '# Night Driving Safety\n\nDriving at night presents unique challenges that require extra caution.\n\n## Challenges of Night Driving\n\n1. **Reduced visibility** — Headlights illuminate only a limited distance\n2. **Glare** — Oncoming headlights can temporarily blind you\n3. **Fatigue** — Natural drowsiness increases at night\n4. **Impaired drivers** — More likely to be on the road at night\n5. **Wildlife** — Animals are more active at dawn and dusk\n\n## Safe Night Driving Practices\n\n### Before Driving\n- Ensure all headlights and taillights are working\n- Clean windshield and mirrors\n- Get enough rest before long night trips\n\n### While Driving\n- Use high beams on unlit roads (dip for oncoming traffic)\n- Reduce speed — you can only see as far as your headlights\n- Increase following distance\n- Take breaks every 2 hours\n- Never drive if feeling drowsy\n\n### Dealing with Glare\n- Look to the left edge of the road when meeting oncoming traffic\n- Avoid looking directly at headlights\n- Use anti-glare settings on your rearview mirror\n\n> **Warning**: Driving while drowsy is as dangerous as drunk driving. If you feel sleepy, pull over safely and rest.\n\n## Key Takeaways\n1. Reduce speed at night — you can only see as far as your headlights\n2. Use high beams on unlit roads but dip for oncoming traffic\n3. Increase following distance\n4. Never drive when drowsy — pull over and rest', 3, 15, 60, false, 15, NULL);

    -- Questions for Module 4
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (4, 1, 'defensive-driving', 'multiple_choice', 'What is the recommended following distance in normal conditions?', '["1 second","2 seconds","3 seconds","5 seconds"]', 2, 'The recommended following distance in normal conditions is 3 seconds. Use the 3-second rule: count after the vehicle ahead passes a fixed point.', 1, true),
    (4, 1, 'defensive-driving', 'multiple_choice', 'On wet roads, your following distance should be:', '["2 seconds","3 seconds","4-5 seconds","6-7 seconds"]', 2, 'On wet roads, increase your following distance to 4-5 seconds. Wet roads increase stopping distance and reduce tire grip.', 1, true),
    (4, 2, 'defensive-driving', 'multiple_choice', 'How far ahead should you scan while driving?', '["5-8 seconds","8-10 seconds","12-15 seconds","20+ seconds"]', 2, 'You should scan 12-15 seconds ahead. This gives you time to identify and react to potential hazards before they become emergencies.', 1, true),
    (4, 2, 'defensive-driving', 'multiple_choice', 'How often should you check your mirrors?', '["Every 2-3 seconds","Every 5-8 seconds","Every 10-15 seconds","Only when changing lanes"]', 1, 'Check your mirrors every 5-8 seconds. Regular mirror checks help you stay aware of traffic around you.', 1, true),
    (4, 3, 'defensive-driving', 'multiple_choice', 'When driving at night, you should:', '["Drive at the same speed as daytime","Reduce speed — you can only see as far as your headlights","Drive faster to reach your destination","Use high beams at all times"]', 1, 'At night, reduce your speed because you can only see as far as your headlights illuminate. This gives you time to react to hazards.', 1, true),
    (4, 3, 'defensive-driving', 'multiple_choice', 'When meeting oncoming traffic at night, you should:', '["Keep high beams on","Look to the left edge of the road","Close your eyes briefly","Speed up to pass quickly"]', 1, 'When meeting oncoming traffic at night, look to the left edge of the road to avoid being blinded by glare. Never use high beams when facing oncoming traffic.', 1, true),
    (4, NULL, 'defensive-driving', 'multiple_choice', 'Driving while drowsy is:', '["Safe if you open the window","As dangerous as drunk driving","Only dangerous on highways","Not a problem for experienced drivers"]', 1, 'Driving while drowsy is as dangerous as drunk driving. If you feel sleepy, pull over safely and rest. Do not try to push through.', 2, true),
    (4, NULL, 'defensive-driving', 'multiple_choice', 'A ball rolling into the road likely means:', '["Nothing","A child may follow","It is a game","The road is safe"]', 1, 'A ball rolling into the road is a clue that a child may follow. Always be prepared to stop when you see objects rolling into the road.', 2, true);

    -- ============================================================
    -- MODULE 5: Alcohol & Driving (Premium)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('alcohol-driving', 'Alcohol & Drug Awareness', 'Understand the effects of alcohol and drugs on driving ability, legal limits, and the consequences of impaired driving in Nigeria.', 'Wine', 5, false, true, 35, 450);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (5, 'alcohol-effects', 'Effects of Alcohol on Driving', '# Effects of Alcohol on Driving\n\nAlcohol significantly impairs your ability to drive safely, even in small amounts.\n\n## How Alcohol Affects Driving\n\n1. **Slower reaction times** — Takes longer to respond to hazards\n2. **Impaired judgment** — Riskier decisions and overconfidence\n3. **Reduced coordination** — Difficulty steering and braking\n4. **Poor vision** — Blurred vision and reduced depth perception\n5. **Drowsiness** — Increased risk of falling asleep at the wheel\n\n## Blood Alcohol Concentration (BAC)\n\n| BAC Level | Effects |\n|-----------|--------|\n| 0.02% | Some loss of judgment |\n| 0.05% | Reduced coordination |\n| 0.08% | Clear impairment |\n| 0.10% | Significant impairment |\n\n## Legal Limit in Nigeria\n\nThe legal BAC limit in Nigeria is **0.05%**. However, the FRSC recommends **zero tolerance** — do not drink any alcohol if you plan to drive.\n\n> **Important**: Even one drink can impair your driving. The safest choice is to not drink at all if you will be driving.\n\n## Key Takeaways\n1. Alcohol impairs reaction time, judgment, and coordination\n2. The legal BAC limit in Nigeria is 0.05%\n3. FRSC recommends zero tolerance\n4. Even small amounts of alcohol affect driving ability', 1, 15, 50, false, 15, NULL),

    (5, 'drug-impairment', 'Drug Impairment & Driving', '# Drug Impairment & Driving\n\nBoth prescription and recreational drugs can impair your ability to drive safely.\n\n## Types of Drugs That Affect Driving\n\n### Prescription Drugs\n- **Antihistamines** — Can cause drowsiness\n- **Painkillers** — May affect reaction time\n- **Antidepressants** — Can cause dizziness\n- **Sleeping pills** — Residual drowsiness\n\n### Recreational Drugs\n- **Cannabis** — Slows reaction time, impairs coordination\n- **Cocaine** — Aggressive driving, poor judgment\n- **Opioids** — Extreme drowsiness, loss of focus\n\n## Warning Signs of Impairment\n\n- Drowsiness or fatigue\n- Dizziness or lightheadedness\n- Blurred or double vision\n- Difficulty concentrating\n- Delayed reactions\n\n## What to Do\n\n1. **Read labels** — Check if medication causes drowsiness\n2. **Ask your doctor** — Whether it is safe to drive\n3. **Do not mix** — Alcohol and drugs amplify effects\n4. **Use alternative transport** — If impaired, do not drive\n\n> **Law**: Driving under the influence of drugs is illegal in Nigeria and carries severe penalties including fines, imprisonment, and license revocation.\n\n## Key Takeaways\n1. Both prescription and recreational drugs can impair driving\n2. Always read medication labels for drowsiness warnings\n3. Never mix alcohol and drugs\n4. Driving under the influence of drugs is illegal', 2, 15, 50, false, 15, NULL);

    -- Questions for Module 5
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (5, 1, 'alcohol-driving', 'multiple_choice', 'What is the legal BAC limit for driving in Nigeria?', '["0.00%","0.05%","0.08%","0.10%"]', 1, 'The legal BAC limit in Nigeria is 0.05%. However, the FRSC recommends zero tolerance — do not drink if you plan to drive.', 1, true),
    (5, 1, 'alcohol-driving', 'multiple_choice', 'How does alcohol affect driving?', '["Improves reaction time","Has no effect if small amount","Slows reaction time and impairs judgment","Makes you more alert"]', 2, 'Alcohol slows reaction times, impairs judgment, reduces coordination, and causes poor vision. Even small amounts can affect driving ability.', 1, true),
    (5, 1, 'alcohol-driving', 'multiple_choice', 'What does FRSC recommend regarding alcohol and driving?', '["One drink is fine","Zero tolerance","Only beer is allowed","Drink after driving"]', 1, 'The FRSC recommends zero tolerance for alcohol when driving. The safest choice is to not drink at all if you will be driving.', 1, true),
    (5, 2, 'alcohol-driving', 'multiple_choice', 'Which prescription drugs can affect driving?', '["None","Antihistamines and painkillers","Only antibiotics","Vitamins"]', 1, 'Antihistamines, painkillers, antidepressants, and sleeping pills can all affect driving. Always read labels and ask your doctor if it is safe to drive.', 1, true),
    (5, 2, 'alcohol-driving', 'multiple_choice', 'Mixing alcohol and drugs:', '["Has no additional effect","Amplifies the effects","Is safe in small amounts","Only affects certain people"]', 1, 'Mixing alcohol and drugs amplifies their effects, making impairment much worse. Never mix alcohol and drugs before driving.', 2, true),
    (5, NULL, 'alcohol-driving', 'multiple_choice', 'Driving under the influence of drugs in Nigeria carries:', '["No penalty","A warning","Severe penalties including fines and imprisonment","Only a small fine"]', 2, 'Driving under the influence of drugs is illegal in Nigeria and carries severe penalties including fines, imprisonment, and license revocation.', 2, true),
    (5, NULL, 'alcohol-driving', 'multiple_choice', 'If your medication causes drowsiness, you should:', '["Drive anyway","Drive slowly","Use alternative transport","Drink coffee and drive"]', 2, 'If your medication causes drowsiness, use alternative transport. Do not drive while impaired, even by prescription medication.', 1, true);

    -- ============================================================
    -- MODULE 6: Emergency Handling (Free)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('emergency-handling', 'Emergency Handling', 'Learn how to handle road emergencies, accidents, breakdowns, and first aid basics. Essential knowledge for every driver.', 'AlertTriangle', 6, true, false, 35, 450);

    INSERT INTO lessons (module_id, slug, title_en, content_en, sort_order, estimated_minutes, xp_reward, is_microlesson, estimated_duration_minutes, microlesson_order)
    VALUES
    (6, 'accident-response', 'Accident Response', '# Accident Response\n\nKnowing what to do at the scene of an accident can save lives.\n\n## Steps to Take at an Accident Scene\n\n### 1. Ensure Safety First\n- Stop your vehicle safely\n- Turn on hazard lights\n- Place warning triangle 45 meters behind the scene\n- Do not put yourself in danger\n\n### 2. Call for Help\n- Call FRSC: **122**\n- Call Police: **199** or **112**\n- Call ambulance if there are injuries\n- Provide clear location information\n\n### 3. Check for Injuries\n- Do not move seriously injured people\n- Check if they are breathing\n- Stop severe bleeding with clean cloth\n- Keep injured persons warm\n\n### 4. Do NOT\n- Do not move vehicles unless they block traffic dangerously\n- Do not give injured persons food or water\n- Do not remove helmets from motorcycle accident victims\n- Do not leave the scene until help arrives\n\n> **Legal Requirement**: Under Nigerian law, you must stop and render assistance if you are involved in or witness an accident. Failing to do so is an offence.\n\n## Key Takeaways\n1. Safety first — use hazard lights and warning triangle\n2. Call FRSC on 122 or 112 for emergencies\n3. Do not move seriously injured people\n4. It is a legal requirement to stop and help', 1, 15, 50, false, 15, NULL),

    (6, 'vehicle-breakdown', 'Vehicle Breakdown Safety', '# Vehicle Breakdown Safety\n\nA vehicle breakdown can be dangerous if not handled correctly.\n\n## What to Do During a Breakdown\n\n### On a Highway\n1. **Turn on hazard lights** immediately\n2. **Move to the shoulder** if possible\n3. **Stay in the vehicle** with seatbelts on\n4. **Call for help** — roadside assistance or FRSC\n5. **Place warning triangle** 45 meters behind vehicle\n\n### If You Cannot Move to the Shoulder\n1. Turn on hazard lights\n2. Place warning triangle behind vehicle\n3. Move all passengers to safety behind the barrier\n4. Do not stand behind or in front of the vehicle\n\n### At Night\n1. Keep hazard lights on\n2. Use a flashlight if available\n3. Stay visible but away from traffic\n4. Wait inside the vehicle if it is safe\n\n> **Warning**: Never try to repair your vehicle on the traffic side of the road. Always work on the side away from traffic.\n\n## Key Takeaways\n1. Turn on hazard lights immediately\n2. Move to the shoulder if possible\n3. Place warning triangle 45 meters behind\n4. Never work on the traffic side of the vehicle', 2, 10, 50, false, 10, NULL),

    (6, 'first-aid-basics', 'First Aid Basics for Drivers', '# First Aid Basics for Drivers\n\nBasic first aid knowledge can help you save lives at an accident scene.\n\n## Essential First Aid Skills\n\n### Stopping Bleeding\n1. Apply firm pressure with a clean cloth\n2. Elevate the wound if possible\n3. Do not remove embedded objects — apply pressure around them\n4. Add more cloth on top if blood soaks through\n\n### Checking Breathing\n1. Look for chest movement\n2. Listen for breathing sounds\n3. Feel for breath on your cheek\n4. If not breathing, begin CPR if trained\n\n### Treating Shock\n1. Lay the person flat on their back\n2. Elevate legs 15-20 cm (unless fractured)\n3. Cover with a blanket or coat\n4. Do not give food or water\n5. Reassure the person\n\n### Burns\n1. Cool with running water for 20 minutes\n2. Do not apply creams or ointments\n3. Cover with clean, non-fluffy cloth\n4. Do not break blisters\n\n> **Important**: Always call for professional medical help first. First aid is to stabilize the person until help arrives.\n\n## Emergency Numbers in Nigeria\n- **FRSC**: 122\n- **Police**: 199 or 112\n- **Emergency**: 112\n\n## Key Takeaways\n1. Apply pressure to stop bleeding\n2. Check breathing and perform CPR if trained\n3. Treat shock by laying person flat and elevating legs\n4. Always call for professional help first', 3, 10, 50, false, 10, NULL);

    -- Questions for Module 6
    INSERT INTO questions (module_id, lesson_id, topic_tag, question_type, question_en, options_en, correct_answer, explanation_en, difficulty, is_mock_test_eligible)
    VALUES
    (6, 1, 'emergency-handling', 'multiple_choice', 'What is the FRSC emergency number?', '["199","122","911","999"]', 1, 'The FRSC emergency number is 122. Call this number for road accidents and emergencies in Nigeria.', 1, true),
    (6, 1, 'emergency-handling', 'multiple_choice', 'How far behind should you place a warning triangle?', '["10 meters","20 meters","45 meters","100 meters"]', 2, 'Place a warning triangle 45 meters behind your vehicle to give approaching drivers enough warning. This is especially important on highways.', 1, true),
    (6, 1, 'emergency-handling', 'multiple_choice', 'At an accident scene, you should:', '["Move injured people immediately","Do not move seriously injured people","Give them water","Remove their helmet"]', 1, 'Do not move seriously injured people unless they are in immediate danger. Moving them can worsen spinal or neck injuries.', 1, true),
    (6, 2, 'emergency-handling', 'multiple_choice', 'During a breakdown on a highway, you should:', '["Stand behind the vehicle","Stay in the vehicle with seatbelts on","Try to repair on the traffic side","Leave the vehicle and walk"]', 1, 'During a breakdown, stay in the vehicle with seatbelts on and hazard lights on. Call for help and wait for assistance.', 1, true),
    (6, 2, 'emergency-handling', 'multiple_choice', 'Where should you place the warning triangle during a breakdown?', '["5 meters behind","20 meters behind","45 meters behind","In front of the vehicle"]', 2, 'Place the warning triangle 45 meters behind your vehicle to give approaching drivers enough time to react.', 1, true),
    (6, 3, 'emergency-handling', 'multiple_choice', 'To stop severe bleeding, you should:', '["Apply ice","Apply firm pressure with a clean cloth","Wash with alcohol","Use a tourniquet immediately"]', 1, 'Apply firm pressure with a clean cloth to stop severe bleeding. Elevate the wound if possible and add more cloth if blood soaks through.', 1, true),
    (6, 3, 'emergency-handling', 'multiple_choice', 'When treating shock, you should:', '["Give the person water","Lay them flat and elevate legs","Make them walk around","Give them food"]', 1, 'To treat shock, lay the person flat on their back and elevate their legs 15-20 cm (unless fractured). Cover with a blanket and do not give food or water.', 1, true),
    (6, NULL, 'emergency-handling', 'multiple_choice', 'The general emergency number in Nigeria is:', '["999","911","112","111"]', 2, 'The general emergency number in Nigeria is 112. You can also call 122 for FRSC or 199 for police.', 1, true),
    (6, NULL, 'emergency-handling', 'multiple_choice', 'For burns, you should:', '["Apply butter or oil","Cool with running water for 20 minutes","Apply ice directly","Break any blisters"]', 1, 'For burns, cool with running water for 20 minutes. Do not apply creams, butter, or ice directly. Cover with clean cloth.', 2, true);

    -- ============================================================
    -- MODULE 7: Mock Test (Free, special slug)
    -- ============================================================
    INSERT INTO modules (slug, title_en, description_en, icon, sort_order, is_free, is_premium, estimated_minutes, xp_reward)
    VALUES ('mock-test', 'Mock Theory Test', 'Practice with FRSC-style questions covering all topics. 40 questions, 30 minutes — just like the real test.', 'FileCheck', 7, true, false, 30, 300);

    -- No lessons for mock test module — it uses questions from all modules

    RAISE NOTICE 'Seed data inserted successfully';
  ELSE
    RAISE NOTICE 'Modules already exist, skipping seed';
  END IF;
END $$;
