-- Add additional questions to scale question bank
-- This migration adds sample questions across different modules and difficulty levels
-- to demonstrate scaling capability. In production, this would be populated with
-- actual FRSC-approved questions.

-- Insert additional easy questions
INSERT INTO questions (module_id, topic_tag, question_en, options_en, answer_en, difficulty, is_scenario, explanation) VALUES
(1, 'traffic_signs', 'What does a circular red sign with a white horizontal bar mean?', '["Stop", "Give way", "No entry", "Speed limit"]', 'Stop', 'easy', FALSE, 'A circular red sign with a white horizontal bar is a STOP sign. You must come to a complete stop before the line.'),
(1, 'traffic_signs', 'What color are warning signs in Nigeria?', '["Red and white", "Yellow and black", "Blue and white", "Green and white"]', 'Yellow and black', 'easy', FALSE, 'Warning signs in Nigeria are yellow with black symbols or text to alert drivers to potential hazards.'),
(2, 'right_of_way', 'Who has the right of way at a roundabout?', '["Vehicles already in the roundabout", "Vehicles entering the roundabout", "Emergency vehicles only", "Larger vehicles"]', 'Vehicles already in the roundabout', 'easy', FALSE, 'Vehicles already in the roundabout have the right of way. Entering vehicles must yield to them.'),
(2, 'right_of_way', 'When should you yield to pedestrians?', '["At all times when they are crossing", "Only at marked crossings", "Only when traffic lights are red", "Never"]', 'At all times when they are crossing', 'easy', FALSE, 'You must yield to pedestrians who are crossing the road, whether at marked crossings or not.'),
(3, 'speed_limits', 'What is the default speed limit in built-up areas in Nigeria?', '["50 km/h", "60 km/h", 80 km/h", "100 km/h"]', '50 km/h', 'easy', FALSE, 'The default speed limit in built-up areas in Nigeria is 50 km/h unless otherwise indicated.'),
(3, 'speed_limits', 'What is the speed limit on expressways in Nigeria?', '["100 km/h", "80 km/h", "120 km/h", "60 km/h"]', '100 km/h', 'easy', FALSE, 'The speed limit on expressways in Nigeria is 100 km/h for private vehicles.'),
(4, 'parking', 'How far from a junction should you not park?', '["10 meters", "5 meters", "15 meters", "20 meters"]', '10 meters', 'easy', FALSE, 'You must not park within 10 meters of a junction to ensure visibility and safety.'),
(4, 'parking', 'Is it legal to park on a pedestrian crossing?', '["No", "Yes, if no one is crossing", "Yes, for 5 minutes only", "Yes, at night"]', 'No', 'easy', FALSE, 'Parking on a pedestrian crossing is illegal at all times as it obstructs pedestrian movement.'),
(5, 'overtaking', 'When should you NOT overtake?', '["On a solid white line", "On a clear straight road", "When the vehicle ahead is slow", "In a 60 km/h zone"]', 'On a solid white line', 'easy', FALSE, 'You must not overtake when there is a solid white line, as it indicates no overtaking is allowed.'),
(5, 'overtaking', 'What should you do before overtaking?', '["Check mirrors and blind spots", "Sound your horn only", "Accelerate immediately", "Flash your lights"]', 'Check mirrors and blind spots', 'easy', FALSE, 'Before overtaking, you must check your mirrors and blind spots to ensure it is safe to do so.');

-- Insert additional medium questions
INSERT INTO questions (module_id, topic_tag, question_en, options_en, answer_en, difficulty, is_scenario, explanation) VALUES
(1, 'traffic_lights', 'What does a flashing amber light mean?', '["Proceed with caution", "Stop if safe to do so", "Prepare to stop", "Speed up"]', 'Proceed with caution', 'medium', FALSE, 'A flashing amber light means you may proceed with caution, yielding to pedestrians and other vehicles.'),
(2, 'right_of_way', 'At an uncontrolled intersection, who goes first?', '["Vehicle on the right", "Vehicle on the left", "Larger vehicle", "Faster vehicle"]', 'Vehicle on the right', 'medium', FALSE, 'At an uncontrolled intersection, the vehicle on the right has the right of way (right-hand rule).'),
(3, 'speed_limits', 'What is the speed limit near schools?', '["30 km/h", "50 km/h", "40 km/h", "60 km/h"]', '30 km/h', 'medium', FALSE, 'The speed limit near schools is typically 30 km/h to protect children.'),
(4, 'parking', 'Can you park on the wrong side of the road at night?', '["No", "Yes, if no oncoming traffic", "Yes, with hazard lights", "Yes, for 10 minutes"]', 'No', 'medium', FALSE, 'Parking on the wrong side of the road at night is illegal as it can cause accidents.'),
(5, 'overtaking', 'When approaching a bend, should you overtake?', '["No", "Yes, if you can see clearly", "Yes, if no other vehicles", "Yes, if you signal"]', 'No', 'medium', FALSE, 'You should never overtake when approaching a bend as you cannot see oncoming traffic.'),
(6, 'vehicle_maintenance', 'What is the minimum tread depth for tires in Nigeria?', '["1.6mm", "2mm", "1mm", "3mm"]', '1.6mm', 'medium', FALSE, 'The minimum legal tread depth for tires in Nigeria is 1.6mm for safety.'),
(7, 'emergency_situations', 'What should you do if your brakes fail?', '["Use engine braking and handbrake", "Accelerate", "Jump out", "Turn off engine"]', 'Use engine braking and handbrake', 'medium', FALSE, 'If brakes fail, use engine braking (downshift) and gradually apply the handbrake to slow down safely.'),
(8, 'alcohol_drugs', 'What is the legal blood alcohol limit in Nigeria?', '["0.05%", "0.08%", "0.02%", "Zero tolerance"]', '0.05%', 'medium', FALSE, 'The legal blood alcohol limit in Nigeria is 0.05% for drivers.');

-- Insert additional hard questions
INSERT INTO questions (module_id, topic_tag, question_en, options_en, answer_en, difficulty, is_scenario, explanation) VALUES
(1, 'traffic_signs', 'What does a blue circle with a white arrow pointing right mean?', '["Mandatory direction", "One-way street", "No right turn", "Right turn allowed"]', 'Mandatory direction', 'hard', FALSE, 'A blue circle with a white arrow indicates a mandatory direction that you must follow.'),
(2, 'right_of_way', 'When two emergency vehicles approach from different directions, who has priority?', '["Both should stop and coordinate", "The one with sirens", "The one on the main road", "The larger vehicle"]', 'Both should stop and coordinate', 'hard', FALSE, 'When emergency vehicles approach from different directions, both should stop and coordinate to avoid collision.'),
(3, 'speed_limits', 'What is the speed limit for commercial vehicles on highways?', '["80 km/h", "100 km/h", "60 km/h", "90 km/h"]', '80 km/h', 'hard', FALSE, 'Commercial vehicles have a lower speed limit of 80 km/h on highways compared to private vehicles.'),
(5, 'overtaking', 'What is the minimum distance you must maintain when overtaking a cyclist?', '["1.5 meters", "1 meter", "2 meters", "0.5 meters"]', '1.5 meters', 'hard', FALSE, 'You must maintain at least 1.5 meters when overtaking a cyclist for their safety.'),
(6, 'vehicle_maintenance', 'How often should you check your tire pressure?', '["Weekly", "Monthly", "Yearly", "Before every trip"]', 'Weekly', 'hard', FALSE, 'Tire pressure should be checked weekly as it affects fuel efficiency, tire wear, and safety.'),
(7, 'emergency_situations', 'What is the correct procedure if your vehicle starts skidding?', '["Steer in the direction of the skid", "Brake hard", "Steer opposite to skid", "Accelerate"]', 'Steer in the direction of the skid', 'hard', FALSE, 'If skidding, steer in the direction of the skid to regain control, then counter-steer to straighten.');

-- Insert scenario-based questions
INSERT INTO questions (module_id, topic_tag, question_en, options_en, answer_en, difficulty, is_scenario, explanation) VALUES
(2, 'right_of_way', 'You are approaching a junction. A pedestrian is waiting to cross but there is no marked crossing. What should you do?', '["Stop and let the pedestrian cross", "Continue driving as you have right of way", "Wave the pedestrian to cross quickly", "Honk to alert the pedestrian"]', 'Stop and let the pedestrian cross', 'medium', TRUE, 'You must stop and yield to pedestrians even at unmarked crossings for their safety.'),
(3, 'speed_limits', 'You are driving in a residential area at 45 km/h. The speed limit sign shows 30 km/h. A child runs into the road. What is your legal position?', '["You were speeding and are liable", "You were within reasonable speed for conditions", "The child is at fault", "Speed limits are only advisory"]', 'You were speeding and are liable', 'hard', TRUE, 'You were exceeding the speed limit and are liable. Speed limits are mandatory, not advisory.'),
(5, 'overtaking', 'You are behind a slow-moving truck on a two-lane road. The road ahead curves to the left. Can you overtake?', '["No, you cannot see oncoming traffic", "Yes, if you accelerate quickly", "Yes, if you signal", "Yes, if the truck is below speed limit"]', 'No, you cannot see oncoming traffic', 'hard', TRUE, 'You cannot overtake when approaching a curve as you cannot see oncoming traffic around the bend.'),
(7, 'emergency_situations', 'You are driving at night and your headlights suddenly fail. What should you do FIRST?', '["Slow down and use hazard lights", "Stop immediately", "Continue at reduced speed", "Use high beams"]', 'Slow down and use hazard lights', 'medium', TRUE, 'First slow down gradually and turn on hazard lights to alert other drivers, then find a safe place to stop.'),
(8, 'alcohol_drugs', 'You had one drink 2 hours ago. You feel fine to drive. Is this legal?', '["It depends on your BAC level", "Yes, you feel fine", "No, any alcohol is illegal", "Yes, after 2 hours"]', 'It depends on your BAC level', 'medium', TRUE, 'Legality depends on your actual blood alcohol concentration (BAC), not how you feel. One drink may still put you over the 0.05% limit.');
